backups:
  schedule_keys:
    monthly: monthly
    nightly: nightly

homelab_user: &main_user cianhatton

samba_group: smbgroup
samba_user: smbuser
users:
  - name: *main_user
    group: *main_user
    passwordless_sudo: true

directories:
  # path on qnap where downloads go
  downloads_dir: /mnt/ssd0/downloads
  # path on qnap where plex transcoding happens
  transcoding_dir: /mnt/ssd0/transcoding
  # path on qnap where movies are stored
  movies_dir: /mnt/mergerfs/media/movies
  # path on qnap where tv shows are stored
  tv_dir: /mnt/mergerfs/media/tv
  # path on qnap where docker compose files are stored
  docker_compose_directory: /etc/docker-compose
  # path where photoprism photos are stored
  photoprism_dir: /mnt/mergerfs/photoprism
  # path to youtube videos
  youtube_dir: /mnt/mergerfs/media/youtube
  # path to where paperless docs will be stored
  documents_dir: /mnt/mergerfs/documents

desired_docker_images:
  - ubuntu:latest

portainer_endpoint: -1
portainer_base_url: "http://qnap:9000"
external_docker_networks: []
portainer_required_files: []
