---
- name: "Linkding | Restore any missing volumes from S3"
  ansible.builtin.include_role:
    name: chatton.docker_backup.docker_s3_volume_restore
  vars:
    docker_backup_s3_volume:
      name: "{{ linkding_portainer_stack_name }}_data"

- name: "Linkding | Update Portainer."
  chatton.portainer.portainer_stack:
    username: '{{ portainer_user }}'
    password: '{{ portainer.password }}'
    base_url: '{{ portainer_base_url }}'
    stack_name: '{{ linkding_portainer_stack_name }}'
    endpoint_id: '{{ portainer_endpoint }}'
    state: "{{ linkding_state }}"
    definition:
      version: '3'
      services:
        linkding:
          labels: "{{ backup_labels }}"
          container_name: "{{ linkding_container_name }}"
          image: "{{ linkding_image }}:{{ linkding_tag }}"
          ports:
            - "{{ linkding_expose_port }}:9090"
          volumes:
            - "data:/etc/linkding/data"
          restart: "{{ restart_policy }}"
      volumes:
        data: {}
