---
- name: "Wireguard Easy | Restore any missing volumes from S3"
  ansible.builtin.include_role:
    name: chatton.docker_backup.docker_s3_volume_restore
  vars:
    docker_backup_s3_volume:
      name: "{{ wireguard_easy_portainer_stack_name }}_data"

- name: "Wireguard Easy | Update Portainer."
  chatton.portainer.portainer_stack:
    username: '{{ portainer_user }}'
    password: '{{ portainer.password }}'
    base_url: '{{ portainer_base_url }}'
    stack_name: '{{ wireguard_easy_portainer_stack_name }}'
    endpoint_id: '{{ portainer_endpoint }}'
    state: "{{ wireguard_easy_state }}"
    definition:
      version: "3.8"
      services:
        wg-easy:
          environment:
            WG_HOST: "remote.cianhatton.ie"
            PASSWORD: "{{ wireguard_easy_password }}"

          image: "{{ wireguard_easy_image }}"
          container_name: "{{ wireguard_easy_container_name }}"
          volumes:
            - data:/etc/wireguard
          ports:
            - "51820:51820/udp"
            - "51821:51821/tcp"
          restart: unless-stopped
          cap_add:
            - NET_ADMIN
            - SYS_MODULE
          sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
      volumes:
        data: {}
