name: E2E
on:
  workflow_dispatch:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the codebase
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8.9
    - name: Install dependencies
      run: make deps
    - name: Test Backup & Restore
      run: make e2e
      env:
        VAULT_KEY: "${{ secrets.VAULT_KEY }}"
