---
# defaults file for setup_linode
ssh_keys:
  - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
label: simple-linode

# hosts that are added to the generated .ini file.
hosts:
- user: root
  ip: "{{my_linode.instance.ipv4[0]}}"
