---
- name: "Vaultwarden | Restore any missing volumes from S3"
  ansible.builtin.include_role:
    name: chatton.docker_backup.docker_s3_volume_restore
  vars:
    docker_backup_s3_volume:
      name: "{{ vaultwarden_portainer_stack_name }}_data"

- name: "Vaultwarden | Update Portainer."
  chatton.portainer.portainer_stack:
    username: '{{ portainer_user }}'
    password: '{{ portainer.password }}'
    base_url: '{{ portainer_base_url }}'
    stack_name: '{{ vaultwarden_portainer_stack_name }}'
    endpoint_id: '{{ portainer_endpoint }}'
    state: "{{ vaultwarden_state }}"
    definition:
      version: '3.3'
      services:
        vaultwarden:
          labels: "{{ backup_labels }}"
          image: "{{ vaultwarden_image }}:{{ vaultwarden_tag }}"
          container_name: "{{ vaultwarden_container_name }}"
          environment:
            WEBSOCKET_ENABLED: "{{ vaultwarden_websocket_enabled }}"
            SENDS_ALLOWED: "{{ vaultwarden_sends_allowed }}"
            EMERGENCY_ACCESS_ALLOWED: "{{ vaultwarden_emergency_access_allowed }}"
            WEB_VAULT_ENABLED: "{{ vaultwarden_webvault_enabled }}"
            DOMAIN: "{{ vaultwarden_domain }}"
            ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
            SIGNUPS_ALLOWED: "{{ vaultwarden_signups_allowed }}"
#            YUBICO_CLIENT_ID: "{{ vault_warden_client_id }}"
#            YUBICO_SECRET_KEY: "{{ vault_warden_secret_key }}"
          restart: "{{ restart_policy }}"
          ports:
            - "{{ vaultwarden_expose_port }}:80"
          volumes:
            - data:/data
      volumes:
        data: {}
