galaxy_info:
  author: Cian Hatton
  namespace: chatton
  description: Setup Samba Shares for my Home Lab.
  license: MIT

  min_ansible_version: "2.1"
  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags: []

dependencies: []
