version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    user: root
    volumes:
      - /etc/config/olivetin:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "1337:1337"
    restart: unless-stopped
