---
roles:
  - src: sprat.mergerfs
  - src: geerlingguy.pip
  - src: geerlingguy.docker
  - src: geerlingguy.samba

collections:
  - name: https://github.com/chatton/ansible-portainer.git
    type: git
    version: support_definition
  - name: https://github.com/chatton/ansible-docker-backup.git
    type: git
    version: master
