---
roles:
  - src: sprat.mergerfs
  - src: geerlingguy.pip
  - src: geerlingguy.docker

collections:
  - name: https://github.com/chatton/ansible-portainer.git
    type: git
    version: master
  - name: https://github.com/chatton/ansible-docker-backup.git
    type: git
    version: master
