---
roles:
  - src: sprat.mergerfs

collections:
  - name: https://github.com/chatton/ansible-portainer.git
    type: git
    version: master
  - name: https://github.com/chatton/ansible-docker-backup.git
    type: git
    version: master
