---
- hosts: servers
  become: true
  vars_files:
    - secrets-vault.yml
  roles:
    - role: 'roles/setup_mergerfs'
      tags: ["mergerfs"]
    - role: 'roles/setup_users'
      tags: ["users"]
    - role: 'roles/setup_samba'
      tags: ["samba"]
    - role: 'roles/setup_docker'
      tags: ["docker"]
    - role: 'roles/setup_portainer'
      tags: ["portainer"]
    - role: 'roles/setup_hosted_services'
      tags: ["services"]
