---
- hosts: qnap
  become: true

  pre_tasks:
    - name: Include vault variables.
      include_vars: "{{vault_file}}"
      tags: ["always"]
    - name: Update Packages
      apt:
        upgrade: dist
        update_cache: true
      tags: ["always"]

  roles:
    - role: 'roles/setup_mergerfs'
      tags: ["mergerfs"]
    - role: 'roles/setup_users'
      tags: ["users"]
    - role: 'roles/setup_samba'
      tags: ["samba"]
    - role: 'roles/setup_docker'
      tags: ["docker"]
    - role: 'roles/setup_portainer'
      tags: ["portainer"]
    - role: 'roles/setup_hosted_services'
      tags: ["services"]

- hosts: linodes
  become: true

  pre_tasks:
    - name: Include vault variables.
      include_vars: "{{vault_file}}"
      tags: ["always"]
    - name: Update Packages
      apt:
        upgrade: dist
        update_cache: true
      tags: ["always"]

  roles:
    - role: 'roles/setup_users'
      tags: ["users"]
    - role: 'roles/setup_samba'
      tags: ["samba"]
    - role: 'roles/setup_docker'
      tags: ["docker"]
    - role: 'roles/setup_hosted_services'
      tags: ["services"]
