---
- hosts: linodes
  tasks:
      # TODO
      # Verify sudoers
      # Verify ssh authorized key
      # Verify docker installed
      # Verify docker images pulled
      # Verify app config files

    - name: Docker Compose Files Exist
      command: "stat {{docker_compose_directory}}/{{ item.name }}/docker-compose.yml"
      with_items: "{{services}}"
      changed_when: false
      register: stat
    - name: Assert all Docker Compose files were created
      assert:
        that: item.rc == 0
      with_items: "{{stat.results}}"
