---
name: CI
on:  # yamllint disable-line rule:truthy
  push:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  # test the role
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - image: geerlingguy/docker-centos8-ansible
            mode: github_releases
          - image: geerlingguy/docker-centos7-ansible
            mode: github_releases
          - image: geerlingguy/docker-fedora32-ansible
            mode: github_releases
          - image: geerlingguy/docker-fedora31-ansible
            mode: github_releases
          - image: geerlingguy/docker-fedora30-ansible
            mode: github_releases
          - image: geerlingguy/docker-ubuntu2004-ansible
            mode: github_releases
          - image: geerlingguy/docker-ubuntu2004-ansible
            mode: package_manager
          - image: geerlingguy/docker-ubuntu1804-ansible
            mode: github_releases
          - image: geerlingguy/docker-ubuntu1604-ansible
            mode: github_releases
          - image: geerlingguy/docker-debian10-ansible
            mode: package_manager
          - image: geerlingguy/docker-debian10-ansible
            mode: github_releases
          - image: geerlingguy/docker-debian9-ansible
            mode: github_releases

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in

      - name: Run molecule tests
        env:
          IMAGE: ${{ matrix.config.image }}
          INSTALL_MODE: ${{ matrix.config.mode }}
        run: molecule -v test

  # publish the role on ansible galaxy
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
