version: '3.2'
services:
  nextcloud:
    labels:
      ie.cianhatton.backup.enabled: "true"
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - data:/var/www/html
volumes:
  data:

networks:
  default:
    name: nextcloud_net
    external: true
