---
nginx_proxy_manager_state: present
nginx_proxy_manager_image: jlesage/nginx-proxy-manager
nginx_proxy_manager_tag: v23.04.1
nginx_proxy_manager_http_expose_port: 80
nginx_proxy_manager_https_expose_port: 443
nginx_proxy_manager_expose_port: 8181
nginx_proxy_manager_container_name: nginx-proxy-manager
nginx_proxy_manager_portainer_stack_name: nginx-proxy-manager
nginx_proxy_manager_puid: 1000
nginx_proxy_manager_pgid: 1000
