---
- hosts: servers
  vars_files:
    - ../variables.yml
  become: true
  tasks:
  - name: Checkout Git Repos
    import_tasks: ../tasks/checkout-git-repos-tasks.yml

  - name: Restart Dashy
    ansible.builtin.command: docker restart dashy
