---
- hosts: servers
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: Install aptitude
    apt:
      name: aptitude
      state: latest
      update_cache: true

  - name: Install Dev Tooling
    import_tasks: ../tasks/install-dev-tooling-tasks.yml

  - name: Install & Configure Sudo
    import_tasks: ../tasks/install-sudo-tasks.yml

  - name: Checkout Git Repos
    import_tasks: ../tasks/checkout-git-repos-tasks.yml

  - name: Install Docker
    import_tasks: ../tasks/install-docker-tasks.yml

  - name: Start Portainer
    tags: "skip-e2e" # we can't mount volumes on test runners.
    command: chdir=/home/cianhatton/checkouts/HomeLab/docker-compose/portainer docker compose up -d
