---
# https://hub.docker.com/_/nextcloud/tags
nextcloud_state: present
nextcloud_image: nextcloud
nextcloud_tag: 28.0.4
nextcloud_expose_port: 8081
nextcloud_container_name: nextcloud
nextcloud_portainer_stack_name: nextcloud
