---

# TODO get volumes from docker-compose.yml

- name: Install Docker Module for Python
  pip:
    name:
      - docker
      - docker-compose

- name: "{{ item.name }} | Docker compose up"
  with_items: "{{ docker_compose_services }}"
  community.docker.docker_compose:
    project_name: "{{ item.name }}"
    definition: "{{ item.definition }}"
