galaxy_info:
  author: Cian Hatton
  namespace: chatton
  description: Configures Mergerfs
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Debian
      versions:
        - all
dependencies: []
