---
- name: Converge
  hosts: all
  vars:
    mergerfs_mounts:
      - path: /mnt/storage
        branches:
          - /mnt/data*
        options: allow_other,use_ino
  roles:
    - role: ansible-role-mergerfs
