# Details about config.
# https://github.com/Lissy93/dashy/blob/master/docs/configuring.md



---
pageInfo:
  title: Home Lab
sections:
  - name: Dashboards
    items:
      - title: Dash Dot
        icon: hl-dashdot
        url: "http://qnap:3010"
      - title: Uptime Kuma
        icon: hl-uptime-kuma
        url: "http://qnap:3001"
  - name: Media Stack
    items:
      - title: Plex
        icon: hl-plex
        url: "http://qnap:32400"
      - title: Sonarr
        icon: hl-sonarr
        url: "http://qnap:8989"
      - title: Radarr
        icon: hl-radarr
        url: "http://qnap:7878"
      - title: Overseerr
        icon: hl-overseerr
        url: "http://qnap:5055"
      - title: Jackett
        icon: hl-jackett
        url: "http://qnap:9117"
      - title: Qbittorrent
        icon: hl-qbittorrent
        url: "http://qnap:15000"
  - name: System Admin
    items:
    - title: Portainer
      description: Manage docker apps using Portainer
      icon: hl-portainer
      url: "http://qnap:9000"
    - title: Webmin
      icon: hl-webmin
      url: "http://qnap:10000"
    - title: Adminer
      description: Manage MariaDB
      icon: hl-adminer
      url: "http://qnap:3307"

appConfig:
  statusCheck: true
  showSplashScreen: false