version: '3.5'
services:
  dashy:
    # https://github.com/Lissy93/dashy
    container_name: dashy
    image: lissy93/dashy
    volumes:
      - ./dashy-config.yml:/app/public/conf.yml
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: always
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
