---

# https://docs.docker.com/engine/install/debian/
- name: Update Packages.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600

- name: Download Packages.
  ansible.builtin.apt:
    pkg: ca-certificates

- name: Create keyring directory if it does not exist.
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download gpg key.
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 'a+r'

- name: Creating docker list.
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ version_codename }} stable

- name: Update Packages.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Download Docker Packages.
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  notify: restart-docker
