# @meta author: Cian Hatton
# @meta description: >
# Role to install docker. It also installs the docker and docker compose python
# modules.
# @end


# following official instructions here: https://docs.docker.com/engine/install/debian/
- name: Install packages using apt
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg2
      - lsb-release
      - pip
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

# TODO: paramaterize this
- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: Install docker packages using apt
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Install Docker Modules for Python
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose

- name: Ensure docker is started
  ansible.builtin.service:
    name: docker
    state: started
