---
- name: Portainer Agent
  community.docker.docker_compose:
    project_name: portainer_agent
    definition:
      version: '3.3'
      services:
        agent:
          ports:
            - '9001:9001'
          container_name: portainer_agent
          restart: always
          volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/var/lib/docker/volumes:/var/lib/docker/volumes'
          image: 'portainer/agent:{{ portainer_agent_version }}'
