# https://app.idrivee2.com/region/IE/buckets/backups/object-storage
version: "3"
services:
  docker-volume-backup:
    container_name: docker-volume-backup
    restart: always
    image: ghcr.io/chatton/docker-volume-backup:v0.3.0
    command:
      - periodic-backups
      - --cron
      - "0 3 * * *"
      - --host-path
      - /mnt/hdds/backups/
      - --retention-days
      - "7"
      - --modes
      - "filesystem,s3"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_ENDPOINT: ${AWS_ENDPOINT}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/hdds/backups:/backups
      - /tmp:/tmp

