---
- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Install Docker Compose Module for Python
  pip:
    name: docker-compose

- name: Install docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

# Change the docker dir.
- name: Stop docker service
  ansible.builtin.service:
    name: docker
    state: stopped

- name: Change volume path
  tags: "skip-e2e"
  copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
        "data-root": "{{docker_daemon_host_path}}"
      }

- name: Backup old files
  tags: "skip-e2e"
  ansible.builtin.shell: cp -r /var/lib/docker /var/lib/docker.bak

- name: Delete old docker directory
  tags: "skip-e2e"
  file:
    state: absent
    path: /var/lib/docker

- name: Start docker service
  tags: "skip-e2e"
  ansible.builtin.service:
    name: docker
    state: started
