version: "3"
services:
  nginx-proxy-manager:
    labels:
      ie.cianhatton.backup.enabled: "true"
    image: jlesage/nginx-proxy-manager
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 8181:8181
      - 80:8080
      - 443:4443
    volumes:
      - "data:/config:rw"
volumes:
  data:
