---
- name: Portainer | Pull images
  docker_image:
    name: ubuntu
    source: pull

- name: Restore any missing volumes from S3 for Potainer.
  ansible.builtin.include_role:
    name: chatton.docker_backup.docker_s3_volume_restore
  vars:
    docker_backup_s3_volume:
      name: portainer_portainer_data

- name: Portainer | Docker compose up
  community.docker.docker_compose:
    project_name: portainer
    definition:
      version: '3.2'
      services:
        portainer:
          labels: "{{ backup_labels}}"
          image: "portainer/portainer-ce:{{ portainer_version }}"
          container_name: portainer
          restart: "{{ restart_policy }}"
          ports:
            - 9000:9000
          volumes:
            - portainer_data:/data
            - /var/run/docker.sock:/var/run/docker.sock
      volumes:
        portainer_data:
