- name: Portainer | Pull images
  docker_image:
    name: ubuntu
    source: pull

- name: Restore any missing volumes from S3 for Potainer.
  ansible.builtin.include_role:
    name: chatton.docker_backup.docker_s3_volume_restore
  vars:
    docker_backup_restore_force: false
    docker_backup_restore_latest_s3_key: true
    docker_backup_fail_on_no_s3_backups: false
    docker_backup_s3_volume:
      name: portainer_portainer_data

- name: Portainer | Docker compose up
  community.docker.docker_compose:
    project_name: portainer
    definition:
      version: '3.2'
      services:
        portainer:
          labels:
            ie.cianhatton.backup.enabled: 'true'
            ie.cianhatton.backup.schedule: nightly
          image: portainer/portainer-ce:{{ portainer_version }}
          container_name: portainer
          restart: unless-stopped
          ports:
          - 9000:9000
          volumes:
          - portainer_data:/data
          - /var/run/docker.sock:/var/run/docker.sock
      volumes:
        portainer_data:
