---
- name: Portainer | Create directory if it does not exist.
  ansible.builtin.file:
    path: '{{ directories.docker_compose_directory }}'
    state: directory
    owner: root
    group: root
    mode: 0440

- name: Portainer | Copy docker compose file.
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: '{{ directories.docker_compose_directory }}/portainer/docker-compose.yml'
    owner: root
    group: root
    mode: 0440

- name: Portainer | Pull images
  docker_image:
    name: ubuntu
    source: pull

- name: Restore any missing volumes from S3 for Potainer.
  ansible.builtin.include_role:
    name: chatton.docker_backup.docker_s3_volume_restore
  vars:
    docker_backup_restore_force: false
    docker_backup_restore_latest_s3_key: true
    docker_backup_fail_on_no_s3_backups: false
    docker_backup_s3_volume:
      name: portainer_portainer_data

- name: Portainer | Docker compose up
  community.docker.docker_compose:
    project_src: '{{ directories.docker_compose_directory }}/portainer'
