---
- name: "Dashy | Update Portainer."
  chatton.portainer.portainer_stack:
    username: '{{ portainer_user }}'
    password: '{{ portainer.password }}'
    base_url: '{{ portainer_base_url }}'
    stack_name: '{{ dashdot_portainer_stack_name }}'
    endpoint_id: '{{ portainer_endpoint }}'
    state: "{{ dashdot_state }}"
    definition:
      services:
        dashdot:
          container_name: "{{ dashdot_container_name}}"
          image: "{{ dashdot_image }}:{{ dashdot_tag }}"
          restart: "{{ restart_policy }}"
          privileged: true
          ports:
            - '{{ dashdot_expose_port }}:3001'
          volumes:
            - /:/mnt/host:ro
