---
vault_file: vault_vars/qnap-vault.yml

portainer_required_templates: []
portainer_endpoint: 34
services: []
docker_compose_services: []
ansible_pull_path: /usr/local/bin/ansible-pull

backup_directories: []
cron_hour: "4"

portainer_roles:
  - role: portainer_minio
  - role: portainer_glances
  - role: portainer_dashdot
