---
vault_file: vault_vars/qnap-vault.yml

portainer_endpoint: 34
services: []
ansible_pull_path: /usr/local/bin/ansible-pull

backup_directories: []
cron_hour: "4"

pihole_volumes:
  dell_app: {}
  dell_dns: {}


mariadb_network: mariadb_net

portainer_roles:
   # mariadb network
  - role: portainer_mariadb
  - role: portainer_bookstack
  - role: portainer_nextcloud
  # individual networks
  - role: portainer_minio
  - role: portainer_glances
  - role: portainer_dashdot
  - role: portainer_dashy
  - role: portainer_diun
  - role: portainer_vaultwarden
  - role: portainer_vikunja
  - role: portainer_linkding
  - role: portainer_gotify
  - role: portainer_overseerr
  - role: portainer_pihole
  - role: portainer_uptime_kuma
  - role: portainer_gitea
