---
vault_file: vault_vars/qnap-vault.yml

portainer_required_templates: []
#portainer_endpoint: 23
services: []

docker_compose_services:
  - name: minio
    definition:
      version: '3'
      services:
        minio:
          image: "minio/minio:RELEASE.2023-06-29T05-12-28Z"
          ports:
            # The API
            - "11000:9000"
            # The web console
            - "11001:9001"
          volumes:
            - minio_storage:/data
          environment:
            # specified in the vault file
            MINIO_ROOT_USER: "{{ minio_username }}"
            MINIO_ROOT_PASSWORD: "{{ minio_password }}"
            MINIO_API_ROOT_ACCESS: "on"
            MINIO_BROWSER_REDIRECT_URL: "http://{{ ansible_default_ipv4.address }}:11000"

          command: server --console-address ":9001" /data
      volumes:
        minio_storage: { }


ansible_pull_path: /usr/local/bin/ansible-pull

backup_directories: []
cron_hour: "4"

# docker options
#docker_daemon_options:
#  hosts:
#    - "tcp://0.0.0.0:2375"
#    - "unix:///var/run/docker.sock"

docker_backup_host_backup_directory: "/tmp"
