---
vault_file: vault_vars/qnap-vault.yml

portainer_required_templates: []
portainer_endpoint: 34
services: []
docker_compose_services: []
ansible_pull_path: /usr/local/bin/ansible-pull

backup_directories: []
cron_hour: "4"

portainer_roles:
  - role: portainer_minio
  - role: portainer_glances
  - role: portainer_dashdot
  - role: portainer_dashy
  - role: portainer_vaultwarden
  - role: portainer_bookstack
  - role: portainer_vikunja
  - role: portainer_linkding
#  - role: portainer_gotify
#  - role: portainer_overseerr
#  - role: portainer_pihole
