# all encrypted variables should go in the linked file.
vault_file: vault_vars/qnap-vault.yml
# any qnap specific variables go here
configure_mergerfs: true
mounts:
  - path: /mnt/mergerfs
    state: mounted
    branches:
      - /mnt/data/device0
      - /mnt/data/device1
      - /mnt/data/device2
    options: allow_other,use_ino


configure_samba: true
portainer_host: true

devices:
  - uuid: a54c1bde-1400-4975-bf24-08c603ca3a11     # /dev/sdc1
    path: /mnt/data/device0
  - uuid: 727dddaa-f7a1-439a-995f-5f4d35322e08     # /dev/sdd1
    path: /mnt/data/device1
  - uuid: f3cff115-9adc-4761-b1e9-e81055f3e0af     # /dev/sda1
    path: /mnt/data/device2
      # SSD for downloads / transcoding
  - uuid: c528bf82-61ab-4f3d-87e0-d1e6e02ef7ec     # /dev/sdf
    path: /mnt/ssd0/

# docker networks to be created before portainer stacks are created.
external_docker_networks:
  - mariadb_net

ansible_pull_path: /home/{{ homelab_user }}/.local/bin/ansible-pull

portainer_endpoint: 2

services:
  - name: gitea
    template_vars:
      image: gitea/gitea
      tag: 1.16.9
  - name: mealie
    template_vars: {}
  - name: overseerr
    template_vars: {}
  - name: nextcloud
    template_vars:
      default_network: mariadb_net
  - name: dashboards
    template_vars: {}
  - name: nginx-proxy-manager
    template_vars: {}
  - name: plex
    template_vars: {}
  - name: uptime-kuma
    template_vars: {}
  - name: vpn-stack
    template_vars: {}
  - name: mariadb
    template_vars:
      default_network: mariadb_net
  - name: photoprism
    template_vars:
      default_network: mariadb_net
  - name: olivetin
    template_vars: {}
