---
vault_file: vault_vars/qnap-vault.yml

portainer_endpoint: 23
services:
  - name: linkding
  - name: pihole
  - name: hasteypaste
  - name: vpn-stack
  - name: dashboards
    template_vars:
      dashy: false
      dashdot: true
      glances: true

ansible_pull_path: /usr/local/bin/ansible-pull

cron_hour: "4"

# docker options
docker_daemon_options:
  hosts:
    - "tcp://0.0.0.0:2375"
    - "unix:///var/run/docker.sock"
