---
vault_file: vault_vars/qnap-vault.yml

docker_backup_aws_s3_encrypt: false
docker_backup_host_backup_directory: "/tmp"

portainer_required_templates:
  - source_file: diun-config.j2
    dest_file_name: diun-config.yml
    dest_directory: /etc/config/diun
    handler: restart-diun

portainer_endpoint: 23
services:
  - name: pihole
  - name: hasteypaste
  - name: diun

ansible_pull_path: /usr/local/bin/ansible-pull

backup_directories: []
cron_hour: "4"

# docker options
docker_daemon_options:
  hosts:
    - "tcp://0.0.0.0:2375"
    - "unix:///var/run/docker.sock"


portainer_roles:
  - role: portainer_bookstack
  - role: portainer_vaultwarden
  - role: portainer_dashy
  - role: portainer_dashdot
  - role: portainer_glances
