---
vault_file: vault_vars/qnap-vault.yml

portainer_required_templates:
  - source_file: diun-config.j2
    dest_file_name: diun-config.yml
    dest_directory: /etc/config/diun
    handler: restart-diun

portainer_endpoint: 35
services:
  - name: hasteypaste

ansible_pull_path: /usr/local/bin/ansible-pull

backup_directories: []
cron_hour: "4"

# Note: this must be inline with the host name,
# this is a work around as it is not possible to template
# the name of the volume in the portainer task.
pihole_volumes:
  snunmu_app: {}
  snunmu_dns: {}

portainer_roles:
  - role: portainer_dashy
  - role: portainer_diun
  - role: portainer_dashdot
  - role: portainer_glances
  - role: portainer_pihole
