---
vault_file: vault_vars/qnap-vault.yml

portainer_endpoint: 23
services:
  - name: linkding
    template_vars: {}
  - name: pihole
  - name: dashboards
    template_vars:
      dashy: false
      dashdot: true
      glances: true

ansible_pull_path: /usr/local/bin/ansible-pull

cron_hour: "4"
