---
galaxy_info:
  author: Sylvain Prat
  role_name: mergerfs
  namespace: sprat
  description: Install and configure Mergerfs — A featureful union filesystem
  license: MIT
  company: none
  min_ansible_version: 2.3
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - mergerfs
    - union
    - filesystem
    - disk
    - mount

dependencies: []
