---
- name: Include vault variables.
  include_vars: defaults/main-vault.yml

- name: Create a new Linode.
  linode_v4:
    label: "{{ label }}"
    access_token: "{{ token }}"
    type: g6-nanode-1
    region: us-east
    image: linode/debian11
    root_pass: "{{ password }}"
    authorized_keys: "{{ ssh_keys }}"
    group: servers
    state: present
  register: my_linode
