---
- name: Include vault variables.
  include_vars: defaults/main-vault.yml

- name: Create a new Linode.
  linode_v4:
    label: "{{ label }}"
    access_token: "{{ token }}"
    type: g6-nanode-1
    region: us-east
    image: linode/debian11
    root_pass: "{{ password }}"
    authorized_keys: "{{ ssh_keys }}"
    group: servers
    state: present
  register: my_linode

- name: Instance Details
  debug:
    msg: "{{my_linode}}"

- name: Template Hosts File
  vars:
    linode_user: root
    linode_ip: "{{my_linode.instance.ipv4[0]}}"
  template:
    src: hosts.j2
    dest: linodehosts.ini
