---
- name: Create snippets directory.
  ansible.builtin.file:
    path: '{{ nginx_proxy_manager_snippets_dir }}'
    state: directory
    mode: '0755'
  notify: restart-nginx-proxy-manager

- name: Create authrequest files.
  notify: restart-nginx-proxy-manager
  ansible.builtin.template:
    src: "authelia-authrequest.j2"
    dest: '{{ nginx_proxy_manager_snippets_dir }}/authelia-authrequest.conf'
    owner: root
    group: root
    mode: 0440

- name: Create authelia-location.conf.
  ansible.builtin.template:
    src: "authelia-location.j2"
    dest: '{{ nginx_proxy_manager_snippets_dir }}/authelia-location.conf'
    owner: root
    group: root
    mode: 0440
  notify: restart-nginx-proxy-manager

- name: Create proxy.conf.
  ansible.builtin.template:
    src: "proxy.j2"
    dest: '{{ nginx_proxy_manager_snippets_dir }}/proxy.conf'
    owner: root
    group: root
    mode: 0440
  notify: restart-nginx-proxy-manager

- name: "Nginx proxy manager | Restore any missing volumes from S3"
  ansible.builtin.include_role:
    name: chatton.docker_backup.docker_s3_volume_restore
  vars:
    docker_backup_s3_volume:
      name: "{{ nginx_proxy_manager_portainer_stack_name }}_data"

- name: "Nginx proxy manager | Update Portainer."
  chatton.portainer.portainer_stack:
    username: '{{ portainer_user }}'
    password: '{{ portainer.password }}'
    base_url: '{{ portainer_base_url }}'
    stack_name: '{{ nginx_proxy_manager_portainer_stack_name }}'
    endpoint_id: '{{ portainer_endpoint }}'
    state: "{{ nginx_proxy_manager_state }}"
    definition:
      version: "3"
      services:
        nginx-proxy-manager:
          labels: "{{ backup_labels }}"
          image: "{{ nginx_proxy_manager_image }}:{{ nginx_proxy_manager_tag }}"
          container_name: "{{ nginx_proxy_manager_container_name }}"
          restart: "{{ restart_policy }}"
          ports:
            - "{{ nginx_proxy_manager_expose_port }}:8181"
            - "{{ nginx_proxy_manager_http_expose_port }}:8080"
            - "{{ nginx_proxy_manager_https_expose_port }}:4443"
          volumes:
            - "data:/config:rw"
            - "{{ nginx_proxy_manager_snippets_dir }}:/snippets:ro"
      volumes:
        data:
