---
- name: Backup Docker Volumes.
  hosts: servers
  become: true
  vars:
    # corrsponds to which category of backups will be used.
    # determined based on the docker labels.
    schedule: weekly

  pre_tasks:
    - name: Include vault variables.
      ansible.builtin.include_vars: '../{{ vault_file }}'
      tags: [ always ]

  tasks:
    - name: Gotify Notification Begin
      ignore_errors: true
      ansible.builtin.include_role:
        name: gotify_message
      vars:
        gotify_message: "Backup started for host {{ inventory_hostname }} at {{ ansible_date_time.iso8601 }}"

    - name: Find Containers With Backup Label
      docker_host_info:
        containers: true
        containers_filters:
          label:
            - "ie.cianhatton.backup.enabled=true"
            - "ie.cianhatton.backup.schedule={{ schedule }}"
      register: filter_output

    - name: Get Container Names
      ansible.builtin.set_fact: container_names="{{ filter_output.containers | map(attribute="Names") | flatten }}"

    - name: Backup Containers with backup label
      ansible.builtin.include_role:
        name: chatton.docker_backup.docker_s3_backup
      vars:
        container_backup: "{{ container_item | regex_replace('^\\/', '') }}"
        docker_backup_retain_count: 3
      with_items: "{{ container_names }}"
      loop_control:
        loop_var: container_item

    - name: Gotify Notification Complete
      ignore_errors: true
      ansible.builtin.include_role:
        name: gotify_message
      vars:
        gotify_message: "Backup finished for host {{ inventory_hostname }} at {{ ansible_date_time.iso8601 }}"
