---
- hosts: qnap
  become: true
  pre_tasks:
  - name: Include vault variables.
    include_vars: '../{{vault_file}}'
    tags: [always]
  roles:
    - role: chatton.docker_backup.docker_s3_volume_restore
      vars:
        docker_s3_volume_restore_force: true
        docker_s3_volume_restore_latest_s3_key: true
        docker_volume_s3_restores:
          - volume_name: "linkding_data"
#            s3_key: "linkding_data/linkding_data-2022-09-01T21:32:54Z.tar.gz"
