---
- name: Restore a docker volume.
  hosts: servers
  become: true
  pre_tasks:
  - name: Include vault variables.
    ansible.builtin.include_vars: '../{{ vault_file }}'
    tags: [always]
  vars:
    volume_name: ""
    s3_key: ""
  roles:
    - role: chatton.docker_backup.docker_s3_volume_restore
      vars:
        docker_backup_restore_force: true
        docker_backup_restore_latest_s3_key: "{{ volume_name != '' | bool }}"
        docker_backup_fail_on_no_s3_backups: true
        docker_backup_s3_volume:
          name: "{{ volume_name }}"
          s3_key: "{{ s3_key }}"
