---
- hosts: qnap
  become: true
  pre_tasks:
  - name: Include vault variables.
    include_vars: '../{{vault_file}}'
    tags: [always]
  roles:
    - role: docker_s3_volume_restore

#  - role: docker_restore_container
#    vars:
#      container_restore: linkding
