---
- name: Update packages and ensure users on all hosts
  tags: [always]
  hosts: all
  become: true
  pre_tasks:
  - name: Update Packages
    apt:
      upgrade: dist
      update_cache: true
  roles:
  - role: setup_users

- name: Install docker on docker hosts
  hosts: dockerhosts
  become: true
  roles:
  - role: setup_docker
    tags: [setup, docker]

- name: Setup and deploy services on the QNAP
  hosts: qnap
  become: true
  pre_tasks:
  - name: Include vault variables.
    include_vars: '../{{vault_file}}'
    tags: [always]

  roles:
  - role: setup_mergerfs
    tags: [mergerfs]
  - role: setup_samba
    tags: [samba]
  - role: setup_portainer
    tags: [services, portainer]
  - role: setup_hosted_services
    tags: [services]


- hosts: linodes
  become: true

  pre_tasks:
  - name: Include vault variables.
    include_vars: '../{{vault_file}}'
    tags: [always]

  roles:
  - role: setup_samba
    tags: [samba]
  - role: setup_docker
    tags: [docker]
  - role: setup_hosted_services
    tags: [services]
