---
- name: Update packages and ensure users on all hosts
  tags: [always]
  hosts: all
  become: true
  pre_tasks:
    - name: Update Packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
  roles:
    - role: setup_users

- name: Setup and deploy services.
  hosts: servers
  become: true
  pre_tasks:
    - name: Include vault variables.
      ansible.builtin.include_vars: '../{{ vault_file }}'
      tags: [always]

  roles:
    - role: setup_mergerfs
      tags: [mergerfs]
      when: configure_mergerfs
    - role: setup_samba
      when: configure_samba
      tags: [samba]
    - role: setup_docker
      tags: [setup, docker]
    - role: setup_portainer
      when: portainer_host
      tags: [services, portainer]
    - role: setup_hosted_services
      tags: [services]

- name: Setup home lab on linode instances.
  hosts: linodes
  become: true
  pre_tasks:
    - name: Include vault variables.
      ansible.builtin.include_vars: '../{{ vault_file }}'
      tags: [always]

  roles:
    - role: setup_samba
      tags: [samba]
    - role: setup_docker
      tags: [docker]
    - role: setup_hosted_services
      tags: [services]
