---
- name: "Christmas | Restore any missing volumes from S3"
  ansible.builtin.include_role:
    name: chatton.docker_backup.docker_s3_volume_restore
  vars:
    docker_backup_s3_volume:
      name: "{{ christmas_portainer_stack_name }}_data"

- name: "Christmas | Update Portainer."
  chatton.portainer.portainer_stack:
    username: '{{ portainer_user }}'
    password: '{{ portainer.password }}'
    base_url: '{{ portainer_base_url }}'
    stack_name: '{{ christmas_portainer_stack_name }}'
    endpoint_id: '{{ portainer_endpoint }}'
    state: "{{ christmas_state }}"
    definition:
      version: "3"
      volumes:
        data: {}
      services:
        christmas-community:
          labels: "{{ backup_labels }}"
          container_name: "{{ christmas_container_name }}"
          image: "{{ christmas_image }}:{{ christmas_tag }}"
          volumes:
            - data:/data
          ports:
            # If you want to go to localhost:8080 to access Christmas Community,
            # use - 8080:80 instead of
            - "{{ christmas_expose_port }}:80"
          environment:
            # Amazon Smile, set to 'false' to disable www.amazon.com links
            # turning into smile.amazon.com
            SMILE: 'false'
            # Table mode, set to 'false' to revert to box mode
            TABLE: 'true'
            # Single list mode
            # (for weddings, birthdays, etc. only the admin account's list is accessible)
            # Set to 'true' to enable
            SINGLE_LIST: 'false'
            # Some websites (like walmart) send headers that are larger than 8MB in
            # length. If issues are encountered, set the node.js limit to a higher
            # number than 8192
            #NODE_OPTIONS: "--max-http-header-size=32768"
          restart: "{{ restart_policy }}"
