---
name: CI
on:
  push:

env:
  VAULT_PASSWORD: "${{ secrets.VAULT_PASSWORD }}"
  SSH_PUB: "${{ secrets.SSH_PUB }}"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH pub
        run: |
          echo "creating ~/.ssh/id_rsa.pub file"
          mkdir -p ~/.ssh/
          echo "$SSH_PUB" > ~/.ssh/id_rsa.pub
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Check out the codebase.
        uses: actions/checkout@v3
      - name: Prepare Test Files
        run: |
          mv tests/.vault-pass.sh ./.vault-pass.sh
          mv tests/ansible.cfg ./ansible.cfg
          mv tests/hosts.ini ./hosts.ini
      - name: Install test dependencies.
        run: |
          sudo python3 -m pip install --upgrade pip
          sudo pip3 install -r requirements.txt
      - name: Syntax Check
        run: |
          ansible-playbook setup-linode.yml --syntax-check
          ansible-playbook setup-homelab.yml --syntax-check
      - name: Setup Linode Instance
        run: |
          ansible-playbook setup-linode.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'
