name: Code Health
on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
        - roles
        - playbooks
        - group_vars
        - host_vars
    steps:
    - name: Checkout the codebase
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.4
    - name: Create Vault Key
      run: echo "${{ secrets.VAULT_PASSWORD }}" > ~/.vault-key
    - name: Install dependencies
      run: make deps
    - name: Test Directory
      run: make lint dir=${{ matrix.directory }}

  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the codebase
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: make deps
    - name: Format code
      run: make format
